#교정날짜 : 23.09.xx
header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: imu
child_frame_id: rsbp_bump_right
transform:
  translation:
    x: 0.8190
    y: 2.9046
    z: 0.5579
  rotation:
    x: 0.5201
    y: 0.4988
    z: 0.4794
    w: 0.5009
