services:
  service:
    build:
      context: ./apps/service
      dockerfile: Dockerfile.laptop
    image: service:1.0.0
    container_name: service
    network_mode: host
    environment:
      - CONFIG_FILE_PATH=config/laptop.json
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./apps/service:/app
