#교정날짜 : 23.09.xx
header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: imu
child_frame_id: at128_roof_rear
transform:
  translation:
    x: -0.0171
    y: -0.4788
    z: 1.1429
  rotation:
    x: 0.6881
    y: -0.7222
    z: -0.0520
    w: -0.0484
