#교정날짜 : 23.08.xx
header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: imu
child_frame_id: at128_roof_right
transform:
  translation:
    x: 0.5494
    y: 1.5256
    z: 1.2638
  rotation:
    x: 0.0017
    y: 0.0846
    z: 0.0128
    w: 0.9963
