#교정날짜 : 23.09
header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: imu
child_frame_id: rsbp_bump_right
transform:
  translation:
    x: 0.7990
    y: 2.9046
    z: 0.5479
  rotation:
    x: 0.5050
    y: 0.5009
    z: 0.4897
    w: 0.5042
