# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gateway_pb2 as gateway__pb2
import service_pb2 as service__pb2


class GatewayStub(object):
    """Device: CPU, VPU 등 HW 장치
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
                '/protos.Gateway/ping',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=service__pb2.void.FromString,
                )
        self.is_dev_connected = channel.unary_unary(
                '/protos.Gateway/is_dev_connected',
                request_serializer=gateway__pb2.Device.SerializeToString,
                response_deserializer=service__pb2.Connection.FromString,
                )
        self.is_all_dev_connected = channel.unary_unary(
                '/protos.Gateway/is_all_dev_connected',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=gateway__pb2.Connections.FromString,
                )
        self.is_dev_healthy = channel.unary_unary(
                '/protos.Gateway/is_dev_healthy',
                request_serializer=gateway__pb2.Device.SerializeToString,
                response_deserializer=service__pb2.Health.FromString,
                )
        self.is_all_dev_healthy = channel.unary_unary(
                '/protos.Gateway/is_all_dev_healthy',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=gateway__pb2.Healths.FromString,
                )
        self.get_sensors = channel.unary_unary(
                '/protos.Gateway/get_sensors',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=service__pb2.Sensors.FromString,
                )
        self.is_sensor_connected = channel.unary_unary(
                '/protos.Gateway/is_sensor_connected',
                request_serializer=service__pb2.Sensor.SerializeToString,
                response_deserializer=service__pb2.Connection.FromString,
                )
        self.is_all_sensor_connected = channel.unary_unary(
                '/protos.Gateway/is_all_sensor_connected',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=gateway__pb2.Connections.FromString,
                )
        self.is_sensor_healthy = channel.unary_unary(
                '/protos.Gateway/is_sensor_healthy',
                request_serializer=service__pb2.Sensor.SerializeToString,
                response_deserializer=service__pb2.Health.FromString,
                )
        self.is_all_sensor_healthy = channel.unary_unary(
                '/protos.Gateway/is_all_sensor_healthy',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=gateway__pb2.Healths.FromString,
                )
        self.get_sensor_snapshot = channel.unary_unary(
                '/protos.Gateway/get_sensor_snapshot',
                request_serializer=service__pb2.Sensor.SerializeToString,
                response_deserializer=service__pb2.SensorSnapshot.FromString,
                )
        self.get_all_sensor_snapshot = channel.unary_unary(
                '/protos.Gateway/get_all_sensor_snapshot',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=service__pb2.SensorSnapshots.FromString,
                )
        self.is_sensor_acquiring = channel.unary_unary(
                '/protos.Gateway/is_sensor_acquiring',
                request_serializer=service__pb2.Sensor.SerializeToString,
                response_deserializer=service__pb2.Acquisition.FromString,
                )
        self.is_all_sensor_acquiring = channel.unary_unary(
                '/protos.Gateway/is_all_sensor_acquiring',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=gateway__pb2.Acquisitions.FromString,
                )
        self.start_sensor_acquisition = channel.unary_unary(
                '/protos.Gateway/start_sensor_acquisition',
                request_serializer=service__pb2.Sensor.SerializeToString,
                response_deserializer=service__pb2.Acquisition.FromString,
                )
        self.start_all_sensor_acquisition = channel.unary_unary(
                '/protos.Gateway/start_all_sensor_acquisition',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=gateway__pb2.Acquisitions.FromString,
                )
        self.stop_sensor_acquisition = channel.unary_unary(
                '/protos.Gateway/stop_sensor_acquisition',
                request_serializer=service__pb2.Sensor.SerializeToString,
                response_deserializer=service__pb2.Acquisition.FromString,
                )
        self.stop_all_sensor_acquisition = channel.unary_unary(
                '/protos.Gateway/stop_all_sensor_acquisition',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=gateway__pb2.Acquisitions.FromString,
                )
        self.add_voice_tag = channel.unary_unary(
                '/protos.Gateway/add_voice_tag',
                request_serializer=gateway__pb2.VoiceTag.SerializeToString,
                response_deserializer=service__pb2.void.FromString,
                )


class GatewayServicer(object):
    """Device: CPU, VPU 등 HW 장치
    """

    def ping(self, request, context):
        """ping 테스트
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_dev_connected(self, request, context):
        """Device 가 정상 작동 중인지 확인. 내부적으로 HW의 OS에 ping을 날려 확인함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_all_dev_connected(self, request, context):
        """모든 Device 가 정상 작동 중인지 확인
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_dev_healthy(self, request, context):
        """Device 에서 service 프로세스가 실행 되고 있는지 확인. Service 서버에 ping 메시지를 날려 확인함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_all_dev_healthy(self, request, context):
        """모든 Device 에서 service 가 실행 되고 있는지 확인
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_sensors(self, request, context):
        """모든 Device 에서 센서 목록을 가져옴.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_sensor_connected(self, request, context):
        """개별 센서의 연결 상태를 확인함. Sensor의 name에는 'device_name/sensor_name' 형태로 입력함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_all_sensor_connected(self, request, context):
        """모든 센서의 연결 상태를 확인함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_sensor_healthy(self, request, context):
        """개별 센서의 정상 작동 상태를 확인함 (센서에서 반환하는 값이 정상 범위 내에 있는지). Sensor의 name에는 'device_name/sensor_name' 형태로 입력함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_all_sensor_healthy(self, request, context):
        """모든 센서의 정상 작동 상태를 확인함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_sensor_snapshot(self, request, context):
        """개별 센서의 스냅샷을 가져옴. Sensor의 name에는 'device_name/sensor_name' 형태로 입력함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_sensor_snapshot(self, request, context):
        """모든 센서의 스냅샷을 가져옴.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_sensor_acquiring(self, request, context):
        """개별 센서의 데이터 취득 상태를 확인함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_all_sensor_acquiring(self, request, context):
        """모든 센서의 데이터 취득 상태를 확인함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_sensor_acquisition(self, request, context):
        """개별 센서의 데이터 취득을 시작함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_all_sensor_acquisition(self, request, context):
        """모든 센서의 데이터 취득을 시작함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop_sensor_acquisition(self, request, context):
        """개별 센서의 데이터 취득을 중지함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop_all_sensor_acquisition(self, request, context):
        """모든 센서의 데이터 취득을 중지함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def add_voice_tag(self, request, context):
        """음성 태그를 저장함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=service__pb2.void.SerializeToString,
            ),
            'is_dev_connected': grpc.unary_unary_rpc_method_handler(
                    servicer.is_dev_connected,
                    request_deserializer=gateway__pb2.Device.FromString,
                    response_serializer=service__pb2.Connection.SerializeToString,
            ),
            'is_all_dev_connected': grpc.unary_unary_rpc_method_handler(
                    servicer.is_all_dev_connected,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=gateway__pb2.Connections.SerializeToString,
            ),
            'is_dev_healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.is_dev_healthy,
                    request_deserializer=gateway__pb2.Device.FromString,
                    response_serializer=service__pb2.Health.SerializeToString,
            ),
            'is_all_dev_healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.is_all_dev_healthy,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=gateway__pb2.Healths.SerializeToString,
            ),
            'get_sensors': grpc.unary_unary_rpc_method_handler(
                    servicer.get_sensors,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=service__pb2.Sensors.SerializeToString,
            ),
            'is_sensor_connected': grpc.unary_unary_rpc_method_handler(
                    servicer.is_sensor_connected,
                    request_deserializer=service__pb2.Sensor.FromString,
                    response_serializer=service__pb2.Connection.SerializeToString,
            ),
            'is_all_sensor_connected': grpc.unary_unary_rpc_method_handler(
                    servicer.is_all_sensor_connected,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=gateway__pb2.Connections.SerializeToString,
            ),
            'is_sensor_healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.is_sensor_healthy,
                    request_deserializer=service__pb2.Sensor.FromString,
                    response_serializer=service__pb2.Health.SerializeToString,
            ),
            'is_all_sensor_healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.is_all_sensor_healthy,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=gateway__pb2.Healths.SerializeToString,
            ),
            'get_sensor_snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.get_sensor_snapshot,
                    request_deserializer=service__pb2.Sensor.FromString,
                    response_serializer=service__pb2.SensorSnapshot.SerializeToString,
            ),
            'get_all_sensor_snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_sensor_snapshot,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=service__pb2.SensorSnapshots.SerializeToString,
            ),
            'is_sensor_acquiring': grpc.unary_unary_rpc_method_handler(
                    servicer.is_sensor_acquiring,
                    request_deserializer=service__pb2.Sensor.FromString,
                    response_serializer=service__pb2.Acquisition.SerializeToString,
            ),
            'is_all_sensor_acquiring': grpc.unary_unary_rpc_method_handler(
                    servicer.is_all_sensor_acquiring,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=gateway__pb2.Acquisitions.SerializeToString,
            ),
            'start_sensor_acquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.start_sensor_acquisition,
                    request_deserializer=service__pb2.Sensor.FromString,
                    response_serializer=service__pb2.Acquisition.SerializeToString,
            ),
            'start_all_sensor_acquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.start_all_sensor_acquisition,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=gateway__pb2.Acquisitions.SerializeToString,
            ),
            'stop_sensor_acquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.stop_sensor_acquisition,
                    request_deserializer=service__pb2.Sensor.FromString,
                    response_serializer=service__pb2.Acquisition.SerializeToString,
            ),
            'stop_all_sensor_acquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.stop_all_sensor_acquisition,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=gateway__pb2.Acquisitions.SerializeToString,
            ),
            'add_voice_tag': grpc.unary_unary_rpc_method_handler(
                    servicer.add_voice_tag,
                    request_deserializer=gateway__pb2.VoiceTag.FromString,
                    response_serializer=service__pb2.void.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Gateway(object):
    """Device: CPU, VPU 등 HW 장치
    """

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/ping',
            service__pb2.void.SerializeToString,
            service__pb2.void.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_dev_connected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/is_dev_connected',
            gateway__pb2.Device.SerializeToString,
            service__pb2.Connection.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_all_dev_connected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/is_all_dev_connected',
            service__pb2.void.SerializeToString,
            gateway__pb2.Connections.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_dev_healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/is_dev_healthy',
            gateway__pb2.Device.SerializeToString,
            service__pb2.Health.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_all_dev_healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/is_all_dev_healthy',
            service__pb2.void.SerializeToString,
            gateway__pb2.Healths.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_sensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/get_sensors',
            service__pb2.void.SerializeToString,
            service__pb2.Sensors.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_sensor_connected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/is_sensor_connected',
            service__pb2.Sensor.SerializeToString,
            service__pb2.Connection.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_all_sensor_connected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/is_all_sensor_connected',
            service__pb2.void.SerializeToString,
            gateway__pb2.Connections.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_sensor_healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/is_sensor_healthy',
            service__pb2.Sensor.SerializeToString,
            service__pb2.Health.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_all_sensor_healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/is_all_sensor_healthy',
            service__pb2.void.SerializeToString,
            gateway__pb2.Healths.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_sensor_snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/get_sensor_snapshot',
            service__pb2.Sensor.SerializeToString,
            service__pb2.SensorSnapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_all_sensor_snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/get_all_sensor_snapshot',
            service__pb2.void.SerializeToString,
            service__pb2.SensorSnapshots.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_sensor_acquiring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/is_sensor_acquiring',
            service__pb2.Sensor.SerializeToString,
            service__pb2.Acquisition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_all_sensor_acquiring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/is_all_sensor_acquiring',
            service__pb2.void.SerializeToString,
            gateway__pb2.Acquisitions.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def start_sensor_acquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/start_sensor_acquisition',
            service__pb2.Sensor.SerializeToString,
            service__pb2.Acquisition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def start_all_sensor_acquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/start_all_sensor_acquisition',
            service__pb2.void.SerializeToString,
            gateway__pb2.Acquisitions.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stop_sensor_acquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/stop_sensor_acquisition',
            service__pb2.Sensor.SerializeToString,
            service__pb2.Acquisition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stop_all_sensor_acquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/stop_all_sensor_acquisition',
            service__pb2.void.SerializeToString,
            gateway__pb2.Acquisitions.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def add_voice_tag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Gateway/add_voice_tag',
            gateway__pb2.VoiceTag.SerializeToString,
            service__pb2.void.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
