# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ping = channel.unary_unary(
                '/protos.Service/ping',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=service__pb2.void.FromString,
                )
        self.get_sensors = channel.unary_unary(
                '/protos.Service/get_sensors',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=service__pb2.Sensors.FromString,
                )
        self.is_connected = channel.unary_unary(
                '/protos.Service/is_connected',
                request_serializer=service__pb2.Sensor.SerializeToString,
                response_deserializer=service__pb2.Connection.FromString,
                )
        self.is_healthy = channel.unary_unary(
                '/protos.Service/is_healthy',
                request_serializer=service__pb2.Sensor.SerializeToString,
                response_deserializer=service__pb2.Health.FromString,
                )
        self.get_snapshot = channel.unary_unary(
                '/protos.Service/get_snapshot',
                request_serializer=service__pb2.Sensor.SerializeToString,
                response_deserializer=service__pb2.SensorSnapshot.FromString,
                )
        self.get_snapshots = channel.unary_unary(
                '/protos.Service/get_snapshots',
                request_serializer=service__pb2.void.SerializeToString,
                response_deserializer=service__pb2.SensorSnapshots.FromString,
                )
        self.is_acquiring = channel.unary_unary(
                '/protos.Service/is_acquiring',
                request_serializer=service__pb2.Sensor.SerializeToString,
                response_deserializer=service__pb2.Acquisition.FromString,
                )
        self.start_acquisition = channel.unary_unary(
                '/protos.Service/start_acquisition',
                request_serializer=service__pb2.Sensor.SerializeToString,
                response_deserializer=service__pb2.Acquisition.FromString,
                )
        self.stop_acquisition = channel.unary_unary(
                '/protos.Service/stop_acquisition',
                request_serializer=service__pb2.Sensor.SerializeToString,
                response_deserializer=service__pb2.Acquisition.FromString,
                )


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ping(self, request, context):
        """ping 테스트
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_sensors(self, request, context):
        """센서 목록을 가져옴.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_connected(self, request, context):
        """센서의 연결 상태를 확인함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_healthy(self, request, context):
        """센서의 정상 작동 여부를 확인함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_snapshot(self, request, context):
        """센서의 현재 스냅샷을 가져옴.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_snapshots(self, request, context):
        """센서들의 현재 스냅샷을 가져옴.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def is_acquiring(self, request, context):
        """센서의 데이터 취득 상태를 확인함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start_acquisition(self, request, context):
        """센서의 데이터 취득을 시작함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop_acquisition(self, request, context):
        """센서의 데이터 취득을 중지함.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=service__pb2.void.SerializeToString,
            ),
            'get_sensors': grpc.unary_unary_rpc_method_handler(
                    servicer.get_sensors,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=service__pb2.Sensors.SerializeToString,
            ),
            'is_connected': grpc.unary_unary_rpc_method_handler(
                    servicer.is_connected,
                    request_deserializer=service__pb2.Sensor.FromString,
                    response_serializer=service__pb2.Connection.SerializeToString,
            ),
            'is_healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.is_healthy,
                    request_deserializer=service__pb2.Sensor.FromString,
                    response_serializer=service__pb2.Health.SerializeToString,
            ),
            'get_snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.get_snapshot,
                    request_deserializer=service__pb2.Sensor.FromString,
                    response_serializer=service__pb2.SensorSnapshot.SerializeToString,
            ),
            'get_snapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.get_snapshots,
                    request_deserializer=service__pb2.void.FromString,
                    response_serializer=service__pb2.SensorSnapshots.SerializeToString,
            ),
            'is_acquiring': grpc.unary_unary_rpc_method_handler(
                    servicer.is_acquiring,
                    request_deserializer=service__pb2.Sensor.FromString,
                    response_serializer=service__pb2.Acquisition.SerializeToString,
            ),
            'start_acquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.start_acquisition,
                    request_deserializer=service__pb2.Sensor.FromString,
                    response_serializer=service__pb2.Acquisition.SerializeToString,
            ),
            'stop_acquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.stop_acquisition,
                    request_deserializer=service__pb2.Sensor.FromString,
                    response_serializer=service__pb2.Acquisition.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Service/ping',
            service__pb2.void.SerializeToString,
            service__pb2.void.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_sensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Service/get_sensors',
            service__pb2.void.SerializeToString,
            service__pb2.Sensors.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_connected(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Service/is_connected',
            service__pb2.Sensor.SerializeToString,
            service__pb2.Connection.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Service/is_healthy',
            service__pb2.Sensor.SerializeToString,
            service__pb2.Health.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Service/get_snapshot',
            service__pb2.Sensor.SerializeToString,
            service__pb2.SensorSnapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_snapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Service/get_snapshots',
            service__pb2.void.SerializeToString,
            service__pb2.SensorSnapshots.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def is_acquiring(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Service/is_acquiring',
            service__pb2.Sensor.SerializeToString,
            service__pb2.Acquisition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def start_acquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Service/start_acquisition',
            service__pb2.Sensor.SerializeToString,
            service__pb2.Acquisition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def stop_acquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protos.Service/stop_acquisition',
            service__pb2.Sensor.SerializeToString,
            service__pb2.Acquisition.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
